apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    app.kubernetes.io/part-of: test-iterate
    apps.tanzu.vmware.com/workload-type: web
    custom-image: "true"
  name: test-image-repo
  namespace: default
spec:
  params:
  - name: image_repository
    value: library
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sample-accelerators/tanzu-java-web-app
